[graph]
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "aarch64-unknown-linux-gnu" },
    { triple = "aarch64-unknown-linux-musl" },
]

[advisories]
ignore = []

[bans]
multiple-versions = "deny"
deny = [
]
skip = [
]

[sources]
allow-git = []

[licenses]
confidence-threshold = 1.0
allow = [
    "Apache-2.0",
    "MIT",
]
exceptions = [
    { name = "decode-lib", allow = ["GPL-3.0"] },
    { name = "decode-lib-fuzz", allow = ["GPL-3.0"] },
    { name = "jwt-decode", allow = ["GPL-3.0"] },
    { name = "tester", allow = ["GPL-3.0"] },
    { name = "linux-rust-bindings", allow = ["MPL-2.0"] },
    { name = "rusl", allow = ["MPL-2.0"] },
    { name = "tiny-start", allow = ["MPL-2.0"] },
    { name = "tiny-std", allow = ["MPL-2.0"] },
    { name = "tiny-cli", allow = ["MPL-2.0"] },
    { name = "unicode-ident", allow = ["Unicode-DFS-2016"] },
]
