[package]
name = "jwt-decode"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"

[dependencies]
decode-lib = { workspace = true }
tiny-std = { workspace = true, features = ["alloc", "executable", "global-allocator"] }
